import 'package:theme_extensions/theme_extension/custom_theme_extension.dart';

/// This is the [CustomThemeExtension] for "Flutter Web Crafters".
final flutterWebCraftersThemeExtension = CustomThemeExtension(
  name: 'Flutter Web Crafters',
  slogan: 'Since Before Flutter Web was Flutter Web',
  streetAddress: '123 Webworks Lane',
  city: 'New York',
  state: 'New York',
  phone: '+1 650 765 4321',
  email: 'web@slingers.flutter',
  logoImage: 'assets/images/hummingbird.png',
  colorPalette: const ThemeExtensionColorPalette(
    primary1: Color(0xFF003C3C),
    primary2: Color(0xFF075151),
    primary3: Color(0xFF477B7B),
    primary4: Color(0xFF779090),
    secondary1: Color(0xFF604C3A),
    secondary2: Color(0xFF85613E),
    secondary3: Color(0xFFCF7A29),
    secondary4: Color(0xFFF47F10),
    onPrimary1: Color(0xFFFFFFFF),
    onPrimary2: Color(0xFFFFFFFF),
    onPrimary3: Color(0xFF333333),
    onPrimary4: Color(0xFF333333),
    onSecondary1: Color(0xFFFFFFFF),
    onSecondary2: Color(0xFFFFFFFF),
    onSecondary3: Color(0xFF333333),
    onSecondary4: Color(0xFF333333),
    onDisabledPrimary1: Color(0xFFFFFFFF),
    onDisabledSecondary1: Color(0xFFFFFFFF),
  ),
  textStyles: CustomThemeExtension.defaultTextStyles,
);

/// This is the [CustomThemeExtension] for "Backend Dartists".
final dartistsThemeExtension = CustomThemeExtension(
  name: 'Backend Dartists',
  slogan: 'Full Stack Dart FTW',
  streetAddress: '123 Serverside Ave',
  city: 'Sunnyvale',
  state: 'California',
  phone: '+1 408 555 1212',
  email: 'solutions@dartists.dev',
  logoImage: 'assets/images/dart.png',
  colorPalette: const ThemeExtensionColorPalette(
    primary1: Color(0xFF235323),
    primary2: Color(0xFF235323),
    primary3: Color(0xFF2EBD2E),
    primary4: Color(0xFF24E924),
    secondary1: Color(0xFF24E924),
    secondary2: Color(0xFF67672C),
    secondary3: Color(0xFFEDED3A),
    secondary4: Color(0xFFFFFF27),
    onPrimary1: Color(0xFFFFFFFF),
    onPrimary2: Color(0xFFFFFFFF),
    onPrimary3: Color(0xFF333333),
    onPrimary4: Color(0xFF333333),
    onSecondary1: Color(0xFFFFFFFF),
    onSecondary2: Color(0xFFFFFFFF),
    onSecondary3: Color(0xFF333333),
    onSecondary4: Color(0xFF333333),
    onDisabledPrimary1: Color(0xFFFFFFFF),
    onDisabledSecondary1: Color(0xFFFFFFFF),
  ),
  textStyles: CustomThemeExtension.defaultTextStyles,
);

/// This is the [CustomThemeExtension] for "Flutter Coders".
final flutterCodersThemeExtension = CustomThemeExtension(
  name: 'Flutter Coders',
  slogan: 'Hitting the target like a Dart',
  streetAddress: '555 Dash Ln',
  city: 'Cleveland',
  state: 'Ohio',
  phone: '+1 123 456 7890',
  email: 'orders@we_make_apps.com',
  logoImage: 'assets/images/flutter.png',
  colorPalette: const ThemeExtensionColorPalette(
    primary1: Color(0xFF6ec3ed ),
    primary2: Color(0xFFFFFFFF),
    primary3: Color(0xFF3656F4),
    primary4: Color(0xFF1a68d3),
    secondary1: Color(0xFF833ef2 ),
    secondary2: Color(0xFFF436E4),
    secondary3: Color(0xFFF4E436),
    secondary4: Color(0xFF833ef2 ),
    onPrimary1: Color(0xFFFFFFFF),
    onPrimary2: Color(0xFF222222),
    onPrimary3: Color(0xFFFFFF27),
    onPrimary4: Color(0xFF619E3C),
    onSecondary1: Color(0xFF222222),
    onSecondary2: Color(0xFF222222),
    onSecondary3: Color(0xFF222222),
    onSecondary4: Color(0xFF222222),
    onDisabledPrimary1: Color(0xFFFFFFFF),
    onDisabledSecondary1: Color(0xFFFFFFFF),
  ),
  textStyles: CustomThemeExtension.defaultTextStyles,
);