import 'package:theme_extensions/theme_extension/theme.dart';

/// This is the [CustomThemeExtension] for "Acme Anvil Company".
final acmeAnvilCompanyThemeExtension = CustomThemeExtension(
  name: 'Acme Anvil Company',
  slogan: 'Special Delivery Hare Mail',
  streetAddress: '123 Nowhere Street',
  city: 'InTheSticks',
  state: 'Kentucky',
  phone: '+500 555 1212',
  email: 'noone@nowhere.net',
  colorPalette: const ThemeExtensionColorPalette(
    primary1: Color(0xFF003C3C),
    primary2: Color(0xFF075151),
    primary3: Color(0xFF477B7B),
    primary4: Color(0xFF779090),
    secondary1: Color(0xFF604C3A),
    secondary2: Color(0xFF85613E),
    secondary3: Color(0xFFCF7A29),
    secondary4: Color(0xFFF47F10),
    onPrimary1: Color(0xFFFFFFFF),
    onPrimary2: Color(0xFFFFFFFF),
    onPrimary3: Color(0xFF333333),
    onPrimary4: Color(0xFF333333),
    onSecondary1: Color(0xFFFFFFFF),
    onSecondary2: Color(0xFFFFFFFF),
    onSecondary3: Color(0xFF333333),
    onSecondary4: Color(0xFF333333),
    onDisabledPrimary1: Color(0xFFFFFFFF),
    onDisabledSecondary1: Color(0xFFFFFFFF),
  ),
  textStyles: CustomThemeExtension.defaultTextStyles,
);

/// This is the [CustomThemeExtension] for "Joe's Bar and Grill".
final joesBarAndGrillThemeExtension = CustomThemeExtension(
  name: 'Joe\'s Bar and Grill',
  slogan: 'Greasy Food Done Right',
  streetAddress: '123 Heart Attack Ln',
  city: 'Burgerland',
  state: 'Texas',
  phone: '+500 555 8899',
  email: 'joe@sliders-r-us.com',
  colorPalette: const ThemeExtensionColorPalette(
    primary1: Color(0xFF0F1E0F),
    primary2: Color(0xFF235323),
    primary3: Color(0xFF2EBD2E),
    primary4: Color(0xFF24E924),
    secondary1: Color(0xFF24E924),
    secondary2: Color(0xFF67672C),
    secondary3: Color(0xFFEDED3A),
    secondary4: Color(0xFFFFFF27),
    onPrimary1: Color(0xFFFFFFFF),
    onPrimary2: Color(0xFFFFFFFF),
    onPrimary3: Color(0xFF333333),
    onPrimary4: Color(0xFF333333),
    onSecondary1: Color(0xFFFFFFFF),
    onSecondary2: Color(0xFFFFFFFF),
    onSecondary3: Color(0xFF333333),
    onSecondary4: Color(0xFF333333),
    onDisabledPrimary1: Color(0xFFFFFFFF),
    onDisabledSecondary1: Color(0xFFFFFFFF),
  ),
  textStyles: CustomThemeExtension.defaultTextStyles,
);

/// This is the [CustomThemeExtension] for "Wingnut Welfare".
final wingnutWelfareThemeExtension = CustomThemeExtension(
  name: 'Wingnut Welfare',
  slogan: 'Funding Crazy Uncle Liberty since 1955',
  streetAddress: '555 Freedom Ln',
  city: 'Self-Righteousville',
  state: 'South Carolina',
  phone: '+997 595 8219',
  email: 'freedom-posts@your-facebook-feed.com',
  colorPalette: const ThemeExtensionColorPalette(
    primary1: Color(0xF4FF3654),
    primary2: Color(0xFFFFFFFF),
    primary3: Color(0xFF3656F4),
    primary4: Color(0xFF000000),
    secondary1: Color(0xFF3CF436),
    secondary2: Color(0xFFF436E4),
    secondary3: Color(0xFFF4E436),
    secondary4: Color(0xFFCCCCCC),
    onPrimary1: Color(0xFFFFFFFF),
    onPrimary2: Color(0xFF222222),
    onPrimary3: Color(0xFFFFFF27),
    onPrimary4: Color(0xFF619E3C),
    onSecondary1: Color(0xFF222222),
    onSecondary2: Color(0xFF222222),
    onSecondary3: Color(0xFF222222),
    onSecondary4: Color(0xFF222222),
    onDisabledPrimary1: Color(0xFFFFFFFF),
    onDisabledSecondary1: Color(0xFFFFFFFF),
  ),
  textStyles: CustomThemeExtension.defaultTextStyles,
);